// Converts @svg-maps/world (CC BY 4.0) into a compact JS module: window.WORLD_MAP
// Usage: node tools/build-map.js path/to/world.svg > map-data.js
const fs = require('fs');
const svg = fs.readFileSync(process.argv[2], 'utf8');
const re = /<path\s+d="([^"]+)"\s+aria-label="([^"]*)"\s+id="([a-z]{2})"/g;
const fmt = n => String(Math.round(n * 10) / 10);
const out = {};
let m;
while ((m = re.exec(svg))) {
  const [, d, , id] = m;
  const subs = [];
  let sx = 0, sy = 0, first = true; // after 'z', a relative 'm' starts from the previous subpath's start
  for (const part of d.split(/[zZ]/)) {
    const t = part.trim();
    if (!/^m/i.test(t)) continue;
    const nums = (t.slice(1).match(/-?\d*\.?\d+(?:e[-+]?\d+)?/gi) || []).map(Number);
    if (nums.length < 2) continue;
    let x = nums[0] + (first ? 0 : sx), y = nums[1] + (first ? 0 : sy);
    first = false; sx = x; sy = y;
    const pts = [[x, y]];
    for (let i = 2; i + 1 < nums.length; i += 2) {
      x += nums[i]; y += nums[i + 1];
      pts.push([x, y]);
    }
    // drop near-duplicate points
    const kept = [pts[0]];
    for (const p of pts.slice(1)) {
      const q = kept[kept.length - 1];
      if (Math.hypot(p[0] - q[0], p[1] - q[1]) >= 0.7) kept.push(p);
    }
    const xs = kept.map(p => p[0]), ys = kept.map(p => p[1]);
    const size = Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...ys) - Math.min(...ys));
    subs.push({ kept, size, pts });
  }
  subs.sort((a, b) => b.size - a.size);
  const keep = subs.filter((s, i) => i === 0 || s.size >= 2);
  // Tiny countries (Vatican, Monaco...) become a small dot so they stay tappable
  if (subs[0] && subs[0].size < 2) {
    const ps = subs[0].pts;
    const cx = ps.reduce((a, p) => a + p[0], 0) / ps.length;
    const cy = ps.reduce((a, p) => a + p[1], 0) / ps.length;
    out[id.toUpperCase()] = `M${fmt(cx - 2)} ${fmt(cy)}a2 2 0 1 0 4 0a2 2 0 1 0-4 0Z`;
    continue;
  }
  out[id.toUpperCase()] = keep
    .filter(s => s.kept.length >= 2)
    .map(s => {
      // relative coords, tracking the rounded position to avoid drift
      let px = Math.round(s.kept[0][0] * 10) / 10, py = Math.round(s.kept[0][1] * 10) / 10;
      let str = 'M' + fmt(px) + ' ' + fmt(py) + 'l';
      for (const p of s.kept.slice(1)) {
        const rx = Math.round(p[0] * 10) / 10, ry = Math.round(p[1] * 10) / 10;
        str += fmt(rx - px) + ' ' + fmt(ry - py) + ' ';
        px = rx; py = ry;
      }
      return str.trim() + 'z';
    })
    .join('');
}
process.stdout.write('// Generated by tools/build-map.js from @svg-maps/world (CC BY 4.0)\nwindow.WORLD_MAP=' + JSON.stringify({ viewBox: '0 0 1010 666', paths: out }) + ';\n');
